/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "前端": {
      "key": "前端",
      "scope": "tags",
      "path": "/tag/前端/",
      "pageKeys": [
        "v-020e9ff6"
      ]
    }
  },
  "categories": {
    "前端": {
      "key": "前端",
      "scope": "categories",
      "path": "/categories/前端/",
      "pageKeys": [
        "v-020e9ff6"
      ]
    }
  },
  "timeline": {}
}